### ISSUE TITLE
Retorno da controller

### ISSUE THREAD

**Issue by foyama** [marcoglnd/go-myapi#1]
Nesse trecho podemos retornar diretamente o func (w WebappController) GetData()(ctx *gin.Context), a gente diminui a complexidade de retornar uma func e fica mais simples
e nas demais controllers também

https://github.com/marcoglnd/go-myapi/blob/234702b2edffbe9897a97543def9ca3e000d9b3a/internal/webapp/controller/controller.go#L20

**Comment by marcoglnd** [comment]
Obrigado pela sugestão, já fiz as alterações que você propôs.
